var GAME_LEVELS = [
  ["                                                                                     ",
   "     m   m   m              o  o  o                       m      m                   ",
   "       m   m                                          m  m m    m m  m               ",
   "             x            xxyyxxyyxxx                  m  m      m  m                ",
   "      xxxxx x                        xx              m        mm      m              ",
   "     x     x                            xx                                           ",
   "     x  o       x                                                                    ",
   "     x        x                                                   xyyyxxx            ",
   "  o  x  o       x                                   xxxyyyyyxx    x!!!!!xxx          ",
   "     x     x                  o      o      xxxx                  x!!!!!x            ",
   "      xxxxx x                                                     x!!!!!x        o   ",
   "             x                     xxxxx                          x!!!!!x            ",
   "                                         xx                        !!!!!     xxyyyx  ",
   "  xxx                                                              !!!!!        o x  ",
   "  x          xxx        o                      xx  o               !!!!!xx        x  ",
   "  x               xyyx                       xx                    !!!!!        o x  ",
   "  x                     o    yyyy                                  !!!!!          x  ",
   "  x  @                                                             !!!!!        o x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxx!!!!!xxxxxxxxxxx  ",
   "                            !!!!!!                    !!!!!        !!!!!             ",
   "                            !!!!!!                    !!!!!        !!!!!             ",
   "                            !!!!!!                    !!!!!        !!!!!             "],
  ["             m       m                                            xxxxxxx                                    x!x  ",
   "           m  m     m m                      o                 xxxx     xxxx       xxx                       x!x  ",
   "                            o    o    !!!xxyyyyyyxx           xx           xx    yy                          x!x  ",
   "            m         m               !!!!!!!!!!!!xxxx       xx             xx  x                            x!x  ",
   "        x       xxx         xxyyxx  xxxxxxxxxxxxx!!x       xxx                                    o   o   o  x!x  ",
   "       x x   m   m   m  x x                     xx!x         x     o   o        x                           xx!x  ",
   "              mm   mm    x                       x!x         x                   yy           xxxxxyyyxxxxxxx!!x  ",
   "                                                 xvx      xxxx     x   x           xxx          !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "  o                                                            xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   " xxx                                           xx   xx                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xxy       x                    ",
   "   xx                             o            xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x            x       ",
   "    yx                        xxx   xxx        xx    x               x   x         x         x                    ",
   "                                x   x          x     x     xyyxxx    x   x   xxxxxxxxx    xxxx         xx         ",
   "xx           xx                 x o x          x    xx               x   x   x               x            o x     ",
   "     @       x                  x   x   o  o   x     x               x   x   x               x                    ",
   "    xxx      x                  x   x    xx    x    xxxxx         xxxx   xxxxx   xyyxxx      x           x        ",
   "    x x      x         xxxyxxy yx o xx         x     x               x     o     y y       yxx                    ",
   "!!!!x x!!!!!!xxxxx     x!!!!!!xy     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     y y         x       x            ",
   "!!!!x x!!!!!!x  o      x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxx  yx  o o  xx          x         ",
   "!!!!x x!!!!!!x         x!!!!!xx   o                 xx!!!!!!xx !                    xx     xx             y       ",
   "!!!!x x!!!!!!x  o  xxxxx!!!!!xx                    xx!!!!!!xx  !                     xxxxxxx               x      ",
   "!!!!x x!!!!!!x         x!!!!!xxx      xxxxxxxxxxxxxx!!!!!!xx   !     o o  o   m    o                     x        ",
   "!!!!x x!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                  xyyxxx          ",
   "!!!!x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !     xxyyxxxxxxxx       xxx                       "],
  ["                                                                                                              ",
   "               o                                                                                              ",
   "              x x                                     mmmm  mmmmm                                             ",
   "                                                    m     m      x                                            ",
   "           x       x                                m  o  m  o   x                                            ",
   "           x o   o x                o   o            m     m     x                                            ",
   "   xx      x       x      xx                          m           m                                           ",
   "  x o xxx    xxxxx    xxx  o       xxxxxx            x              m                                         ",
   "  x      xx         xx     x            x          xx               m                                         ",
   "    x          o          x     x       x                                                                     ",
   "    x     x         x     x     xx      x     xxxxxyyyyyxxxxx      xxx                                        ",
   "     yyyx    xxxxx    xyyy             xxx                                                                    ",
   "               o                       x x                 !!!        !!!  xxx                                ",
   "             o   o              xx     x x                 !x!        !x!                                     ",
   "           xxxyyyxxx             xxyyxxx xxx                x          x                                      ",
   "                                      x   x                 x   o  o   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx                x                                                 ",
   "                                      x   xyyyxxxxx   xxxxxxx               x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   xxx         x                     xxx                               ",
   "                                     xx   x           x                                                       ",
   "                                      x   xxxxxyyy    y            xxx                                        ",
   "                                      x   x           y           x!!!x                                       ",
   "                                      x   x    xxxxx  x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx    o   o x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                          xx x                    xxx xxxxxxxxxxxxxxxx                                        ",
   "                       xxx   xx                     x      x                         xxx                      ",
   "  xxx                xx    x  x     yyxxxxyyxx    xx  xxx  x                        x   x                xxx  ",
   "  x x               x   xx    x   x x        x           xx                         x o xxx              x x  ",
   "  x                  xxx      x   x x      o xxxxx                       xxyyx                    o        x  ",
   "  x                           x            x        o         o          x   x     xx                      x  ",
   "  x                           xx          xxxx                           x o x          x         o        x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx          x                  x  ",
   "  x                xxx             o o    x                              x         xxx            o        x  ",
   "  x               xxxxx       xx          x                             xxx       x   x                    x  ",
   "  x               oxxxo       x    xxx    x                             x x         o y         xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx          y         xxx    o   x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx         x         xxx        x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                            x     x    xxxxx    x     x         xxxxx      xxxxx     xx    x                  ",
   "                            x     x   x     x   x     x        x     x    x     x    x x   x                  ",
   "                            x     x   x     x   x     x        x          x     x    x  xx x                  ",
   "                             xx xx    x     x   x     x        x          xxxxxxx    x    xx                  ",
   "                               x      x     x   x     x        x          x     x    x    xx                  ",
   "                               x      x     x   x     x        x     x    x     x    x     x                  ",
   "                               x       xxxxx     xxxxx          xxxxx     x     x    x     x                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                        xxxxxxx   x         x      x                xxxxxx                                    ",
   "                        x         x         x      x              xx      xx                                  ",
   "                        x         x         x      x             x          x   xx  x                         ",
   "                        xxxxxxx   x          xx  xx              x                 x                          ",
   "                        x         x             x                  xxx            xx                          ",
   "                        x         x             x                     xx          x                           ",
   "                        x         xxxxxxx       x                  x    x           xxxxx                     ",
   "                                                                      xx   x x           x                    ",
   "                                                                  x       xx  x          x                    ",
   "                                                                    x   x       xxx   xx                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
